### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by thanone2** [Blueforcer/PlayniteShell#1]
Will this work with Steam Big Picture Mode? Or does that require a different script?

**Comment by Blueforcer** [comment]
This has nothing to to with steam.
Its a complete different games UI

**Comment by thanone2** [comment]
😑Did you think I didn't know that?

**Comment by Blueforcer** [comment]
Yes, otherwise you could have answered the question yourself.
Maybe ask more detailed If it didn't meet your expectations.

**Comment by thanone2** [comment]
I asked does steam big picture require a different script, NOT is steam big picture the same as playnite.

**Comment by thanone2** [comment]
You know what, nvm

**Comment by Blueforcer** [comment]
How should I know that you know? 
I have a lot of projects and you have no idea what kind of questions come up, so I always start from the beginning because I have to assume that the user has little or no idea. It usually doesn't work the other way around.

But since you seem to know that this script is for playnite, you should also know that it logically can't work for Steam without modifications.
So the question was pretty unnecessary.
But I'll be honest, because of your harsh nature I don't feel like helping you either.
Have a nice evening.
